### ISSUE TITLE
Seagulls in DBP27 not targeted by hitscan weapons

### ISSUE THREAD

**Issue by kvsari** [Helion-Engine/Helion#555] opened 2024-01-04 13:47 UTC
[DBP27](https://doomer.boards.net/thread/1846/dbp27-10-day-vacation) has an error that begins on MAP02. The Seagull custom monster cannot be killed by hitscan weapons such as the shotgun, chaingun or super shotgun. They can be killed with the rocket launcher but considering all the places you encounter the enemy this is not practical and the mapset I daresay cannot be completed.

This WAD is in Doom2 map format for limit removing source ports and intended to be played on complevel 2.This WAD works fine in other source ports such as dsda-doom and gzdoom.

I'd love to play this WAD in your engine.

**Comment by nstlaurent** [comment] 2024-01-04 18:41
I see what the problem is. The seagulls aren't solid but Doom would allow missiles and hitscans to hit if they are shootable. I can update to match that functionality. I pushed the changes to dev. If you are building from source you can pull and get the fix. Otherwise I can make a build later.

**Comment by kvsari** [comment] 2024-01-06 12:51
Thank you so much! If you could please make a build later that would be nice. Otherwise I can wait for the next release, it's no problem for me.

**Comment by nstlaurent** [comment] 2024-01-10 13:32
Here is a newer build that I just made to resolve a problem someone is having compiling on a specific GPU. Should resolve this seagull issue.

[Helion 0.9.2.7](https://www.dropbox.com/scl/fi/vjxah43vy5u2fw49goif9/Helion-0.9.2.7-win-x64-with-Runtime.zip?rlkey=l4louks8m3941b6c5uxd0s4ok&dl=0)

**Comment by nstlaurent** [comment] 2024-03-30 09:40
Fixed with 0.9.2.7

**Closed as completed by nstlaurent** 2024-03-30 09:40 UTC
